/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.ActionEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import logica.EmpleadoLogica;
import modelo.Empleado;
import persistencia.EmpleadoJpaController;

/**
 *
 * @author Joan
 */
public class CrudEmpleados extends javax.swing.JDialog {
//private Empleado empleados;
    /**
     * Creates new form CrudEmpleados
     */
    public CrudEmpleados(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Buscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        UpdateNombre = new javax.swing.JTextField();
        UpdateApellido = new javax.swing.JTextField();
        UpdateDireccion = new javax.swing.JTextField();
        UpdateTelefono = new javax.swing.JTextField();
        UpdateCargo = new javax.swing.JTextField();
        UpdateCedula = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        UpdateEstado = new javax.swing.JTextField();
        Actualizar = new javax.swing.JButton();
        Agregar = new javax.swing.JButton();
        UpdateCorreo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        UpdateContraseña = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("Formulario Para Actualización De Empleados");

        jLabel2.setText("nombre");

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        jLabel3.setText("apellido");

        jLabel4.setText("cargo");

        jLabel5.setText("direccion");

        jLabel6.setText("estado");

        jLabel7.setText("telefono");

        UpdateCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateCedulaActionPerformed(evt);
            }
        });

        jLabel8.setText("cedula del empleado que desea actualizar");

        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });

        Agregar.setText("Agregar");
        Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarActionPerformed(evt);
            }
        });

        jLabel9.setText("correo electronico");

        jLabel10.setText("contraseña");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(UpdateApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                    .addComponent(UpdateCargo)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Buscar)
                                .addGap(18, 18, 18)
                                .addComponent(Actualizar)
                                .addGap(18, 18, 18)
                                .addComponent(Agregar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(UpdateEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(UpdateTelefono))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(UpdateDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(UpdateNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 305, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(UpdateCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UpdateCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UpdateContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UpdateNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpdateCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(UpdateCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(UpdateDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(UpdateEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(UpdateTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(UpdateCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(UpdateContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Buscar)
                    .addComponent(Actualizar)
                    .addComponent(Agregar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
       

       
       //aqui se busca empleado
     
       String cedula = UpdateCedula.getText();
      
       if(cedula.isEmpty()){
            JOptionPane.showMessageDialog(null, "Se requiere el numero de identidad del empleado para realizar su consulta");
       }
       else {
           Empleado emBus = new Empleado();
           emBus.setCedula(cedula);
            EmpleadoLogica pl = new EmpleadoLogica();
            pl.buscarEmpleado(emBus);

           //String ceNumero = new String(cedula);
               

                if (pl.buscarEmpleado(emBus) == null) {
                    JOptionPane.showMessageDialog(null, "El empleado ingresado no radica en la base de datos del sistema");

                } else {
String Estado = String.valueOf(pl.buscarEmpleado(emBus).getEstado());
                    
                  UpdateNombre.setText(pl.buscarEmpleado(emBus).getNombre());
                    UpdateApellido.setText(pl.buscarEmpleado(emBus).getApellidos());

                    UpdateCargo.setText(pl.buscarEmpleado(emBus).getCargo());
                    UpdateDireccion.setText(pl.buscarEmpleado(emBus).getDireccion());
                    UpdateEstado.setText(Estado);
                    UpdateTelefono.setText(pl.buscarEmpleado(emBus).getTelefono());
                    UpdateCorreo.setText(pl.buscarEmpleado(emBus).getCorreo());
                   UpdateContraseña.setText(pl.buscarEmpleado(emBus).getContrasenia());
                   
                  

                }
            }
    }//GEN-LAST:event_BuscarActionPerformed

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        // TODO add your handling code here:
        
        String cedula = UpdateCedula.getText();
     Empleado emActualizado = new EmpleadoLogica().buscarEmpleado(new Empleado(cedula));
        String correo = UpdateCorreo.getText();
        String nombre = UpdateNombre.getText();
        String apellido = UpdateApellido.getText();
        String cargo = UpdateCargo.getText();
        String direccion = UpdateDireccion.getText();
        String estado = UpdateEstado.getText();
        String telefono = UpdateTelefono.getText();
        String contraseña = UpdateContraseña.getText();
   
           
           emActualizado.setCedula(cedula);
           emActualizado.setApellidos(apellido);
           emActualizado.setCorreo(correo);
           emActualizado.setCargo(cargo);
           emActualizado.setContrasenia(contraseña);
           emActualizado.setNombre(nombre);
           emActualizado.setDireccion(direccion);
           emActualizado.setTelefono(telefono);
           
           Boolean emEstado = new Boolean(estado);
           emActualizado.setEstado(emEstado);
           
           EmpleadoLogica pl = new EmpleadoLogica();
        try {
            pl.actualizarEmpleado(emActualizado);
            JOptionPane.showMessageDialog(rootPane, "el empleado ha sido actualizado correctamente");
            
            
            
            
            //pl.actualizarEmpleado(emActualizado.setNombre(UpdateNombre.getText()));
            
            //emBus.setNombre(nombre);
            
            //emBus.setApellidos(apellido);
            
            //emBus.setCargo(cargo);
            
            //emBus.setDireccion(direccion);
            
            //Boolean estadoEm = new Boolean(estado);
            //emBus.setEstado(estadoEm);
            
            //emBus.setTelefono(telefono);
            
            //emBus.setCorreo(correo);
            
            //emBus.setContrasenia(contraseña);
        } catch (Exception ex) {
            Logger.getLogger(CrudEmpleados.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "no se pudo actualizar el empleado");
        }
        
       

       

        UpdateCorreo.setText("");
        UpdateNombre.setText("");
        UpdateApellido.setText("");
        UpdateCedula.setText("");
        UpdateDireccion.setText("");
        UpdateCargo.setText("");
        UpdateEstado.setText("");
        UpdateTelefono.setText("");
        UpdateContraseña.setText("");
    }//GEN-LAST:event_ActualizarActionPerformed

    private void AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarActionPerformed
        // TODO add your handling code here:
        String correo = UpdateCorreo.getText();
        String nombre = UpdateNombre.getText();
        String apellido = UpdateApellido.getText();
        String cargo = UpdateCargo.getText();
        String direccion = UpdateDireccion.getText();
        String estado = UpdateEstado.getText();
        String telefono = UpdateTelefono.getText();
        String cedula = UpdateCedula.getText();
String contraseña = UpdateContraseña.getText();
        
        if (UpdateCedula.getText().equals("") || UpdateTelefono.getText().equals("") || UpdateEstado.getText().equals("") || UpdateDireccion.getText().equals("") || UpdateCargo.getText().equals("") || UpdateApellido.getText().equals("") || UpdateNombre.getText().equals("") || UpdateCorreo.getText().equals("") || UpdateContraseña.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Todos los campos deben estar llenos para poder ingresar un empleado");
        } else {

            Empleado empleado = new Empleado();

            
            
            
            empleado.setContrasenia(contraseña);
            
            empleado.setCorreo(correo);
            //Integer numCu = new Integer(numCuenta);
            //cuenta.setCueNumero(numCu);
            empleado.setCedula(cedula);

            //Float salCu = new Float(saldoCuenta);
            //cuenta.setCueSaldo(salCu);
            empleado.setTelefono(telefono);
            
            //cuenta.setCueClave(claveCuenta);
            Boolean esEmp = new Boolean(estado);
            empleado.setEstado(esEmp);
            
            //Integer cliCe = new Integer(cliCedula);
            //cuenta.setClientesclicedula(cliCe);
            empleado.setDireccion(direccion);
            
            //cuenta.setCueActiva(activaCuenta);
            empleado.setCargo(cargo);
            
            empleado.setApellidos(apellido);
            
            empleado.setNombre(nombre);
            
            EmpleadoLogica pl = new EmpleadoLogica();
            try {
                pl.registarEmpleado(empleado);
                JOptionPane.showMessageDialog(this, "Se agrego el empleado " + UpdateNombre.getText() + " al sistema");
            } catch (Exception ex) {
                Logger.getLogger(CrudEmpleados.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            //EntityManagerFactory conexion = Persistence.createEntityManagerFactory("Peaje1.0PU");
           // EmpleadoJpaController empleadoDao = new EmpleadoJpaController(conexion);

          //  try {
               // empleadoDao.create(empleado);
            //} catch (Exception ex) {
               // System.out.println(ex);
            //}
           // int totalCuentas = empleadoDao.getCuentasCount();
            

            UpdateContraseña.setText("");
            UpdateCorreo.setText("");
            UpdateNombre.setText("");
        UpdateApellido.setText("");
        UpdateCedula.setText("");
        UpdateDireccion.setText("");
        UpdateCargo.setText("");
        UpdateEstado.setText("");
        UpdateTelefono.setText("");

        }

    }//GEN-LAST:event_AgregarActionPerformed

    private void UpdateCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateCedulaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CrudEmpleados dialog = new CrudEmpleados(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Actualizar;
    public javax.swing.JButton Agregar;
    public javax.swing.JButton Buscar;
    public javax.swing.JTextField UpdateApellido;
    public javax.swing.JTextField UpdateCargo;
    public javax.swing.JTextField UpdateCedula;
    public javax.swing.JTextField UpdateContraseña;
    public javax.swing.JTextField UpdateCorreo;
    public javax.swing.JTextField UpdateDireccion;
    public javax.swing.JTextField UpdateEstado;
    public javax.swing.JTextField UpdateNombre;
    public javax.swing.JTextField UpdateTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
