/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Duvan Quevedo
 */
public class VenPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VenPrincipal
     */
    int modNoc = -1;

    public VenPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        modoNocturnoBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        botonsito = new rsbuttom.RSButtonMetro();
        jLabel47 = new javax.swing.JLabel();
        nombreCarril2 = new javax.swing.JTextField();
        jSeparator28 = new javax.swing.JSeparator();
        nombreCarrilBusqueda4 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        nombreCarril3 = new javax.swing.JTextField();
        jSeparator29 = new javax.swing.JSeparator();
        jLabel49 = new javax.swing.JLabel();
        nombreCarril4 = new javax.swing.JTextField();
        jSeparator30 = new javax.swing.JSeparator();
        jLabel50 = new javax.swing.JLabel();
        nombreCarril5 = new javax.swing.JTextField();
        jSeparator31 = new javax.swing.JSeparator();
        jSeparator32 = new javax.swing.JSeparator();
        nombreCarril6 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        nombreCarril7 = new javax.swing.JTextField();
        jSeparator33 = new javax.swing.JSeparator();
        jLabel53 = new javax.swing.JLabel();
        nombreCarril8 = new javax.swing.JTextField();
        jSeparator34 = new javax.swing.JSeparator();
        jLabel54 = new javax.swing.JLabel();
        nombreCarril9 = new javax.swing.JTextField();
        jSeparator35 = new javax.swing.JSeparator();
        jLabel55 = new javax.swing.JLabel();
        nombreCarril10 = new javax.swing.JTextField();
        jSeparator36 = new javax.swing.JSeparator();
        rSButtonMetro2 = new rsbuttom.RSButtonMetro();
        rSButtonMetro3 = new rsbuttom.RSButtonMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-exit.png"))); // NOI18N
        jButton1.setText("Cerrar sesión");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        modoNocturnoBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        modoNocturnoBtn.setForeground(new java.awt.Color(52, 152, 219));
        modoNocturnoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-idea-30.png"))); // NOI18N
        modoNocturnoBtn.setText("Modo nocturno");
        modoNocturnoBtn.setBorderPainted(false);
        modoNocturnoBtn.setContentAreaFilled(false);
        modoNocturnoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoNocturnoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modoNocturnoBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(modoNocturnoBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(73, 171, 213));

        botonsito.setText("Facturar");
        botonsito.setColorHover(new java.awt.Color(73, 171, 213));
        botonsito.setColorNormal(new java.awt.Color(63, 192, 220));
        botonsito.setColorPressed(new java.awt.Color(73, 171, 213));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonsito, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(botonsito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel47.setFont(new java.awt.Font("ClementePDai", 0, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(73, 171, 213));
        jLabel47.setText("ID factura");

        nombreCarril2.setEditable(false);
        nombreCarril2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        nombreCarril2.setForeground(new java.awt.Color(73, 171, 213));
        nombreCarril2.setBorder(null);

        nombreCarrilBusqueda4.setBackground(new java.awt.Color(245, 245, 245));
        nombreCarrilBusqueda4.setFont(new java.awt.Font("ClementePDai", 0, 24)); // NOI18N
        nombreCarrilBusqueda4.setForeground(new java.awt.Color(73, 171, 213));
        nombreCarrilBusqueda4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreCarrilBusqueda4.setText("Factura");

        jLabel48.setFont(new java.awt.Font("ClementePDai", 0, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(73, 171, 213));
        jLabel48.setText("Placa");

        nombreCarril3.setEditable(false);
        nombreCarril3.setBackground(new java.awt.Color(255, 255, 255));
        nombreCarril3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        nombreCarril3.setForeground(new java.awt.Color(73, 171, 213));
        nombreCarril3.setBorder(null);

        jLabel49.setFont(new java.awt.Font("ClementePDai", 0, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(73, 171, 213));
        jLabel49.setText("Categoria");

        nombreCarril4.setEditable(false);
        nombreCarril4.setBackground(new java.awt.Color(255, 255, 255));
        nombreCarril4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        nombreCarril4.setForeground(new java.awt.Color(73, 171, 213));
        nombreCarril4.setBorder(null);

        jLabel50.setFont(new java.awt.Font("ClementePDai", 0, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(73, 171, 213));
        jLabel50.setText("ID carril");

        nombreCarril5.setEditable(false);
        nombreCarril5.setBackground(new java.awt.Color(255, 255, 255));
        nombreCarril5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        nombreCarril5.setForeground(new java.awt.Color(73, 171, 213));
        nombreCarril5.setBorder(null);

        nombreCarril6.setEditable(false);
        nombreCarril6.setBackground(new java.awt.Color(255, 255, 255));
        nombreCarril6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        nombreCarril6.setForeground(new java.awt.Color(73, 171, 213));
        nombreCarril6.setBorder(null);

        jLabel51.setFont(new java.awt.Font("ClementePDai", 0, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(73, 171, 213));
        jLabel51.setText("cedula propietario");

        jLabel52.setFont(new java.awt.Font("ClementePDai", 0, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(73, 171, 213));
        jLabel52.setText("fecha");

        nombreCarril7.setEditable(false);
        nombreCarril7.setBackground(new java.awt.Color(255, 255, 255));
        nombreCarril7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        nombreCarril7.setForeground(new java.awt.Color(73, 171, 213));
        nombreCarril7.setBorder(null);

        jLabel53.setFont(new java.awt.Font("ClementePDai", 0, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(73, 171, 213));
        jLabel53.setText("Hora");

        nombreCarril8.setEditable(false);
        nombreCarril8.setBackground(new java.awt.Color(255, 255, 255));
        nombreCarril8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        nombreCarril8.setForeground(new java.awt.Color(73, 171, 213));
        nombreCarril8.setBorder(null);

        jLabel54.setFont(new java.awt.Font("ClementePDai", 0, 18)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(73, 171, 213));
        jLabel54.setText("Pago");

        nombreCarril9.setEditable(false);
        nombreCarril9.setBackground(new java.awt.Color(255, 255, 255));
        nombreCarril9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        nombreCarril9.setForeground(new java.awt.Color(73, 171, 213));
        nombreCarril9.setBorder(null);

        jLabel55.setFont(new java.awt.Font("ClementePDai", 0, 18)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(73, 171, 213));
        jLabel55.setText("Cambio");

        nombreCarril10.setEditable(false);
        nombreCarril10.setBackground(new java.awt.Color(255, 255, 255));
        nombreCarril10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        nombreCarril10.setForeground(new java.awt.Color(73, 171, 213));
        nombreCarril10.setBorder(null);

        rSButtonMetro2.setText("Facturar");
        rSButtonMetro2.setColorHover(new java.awt.Color(73, 171, 213));
        rSButtonMetro2.setColorNormal(new java.awt.Color(63, 192, 220));
        rSButtonMetro2.setColorPressed(new java.awt.Color(73, 171, 213));

        rSButtonMetro3.setText("Reportar");
        rSButtonMetro3.setColorHover(new java.awt.Color(221, 75, 57));
        rSButtonMetro3.setColorNormal(new java.awt.Color(221, 75, 80));
        rSButtonMetro3.setColorPressed(new java.awt.Color(221, 75, 57));
        rSButtonMetro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(nombreCarrilBusqueda4, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel50)
                                            .addComponent(nombreCarril5)
                                            .addComponent(jSeparator31, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel51)
                                            .addComponent(nombreCarril6)
                                            .addComponent(jSeparator32, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel52)
                                            .addComponent(nombreCarril7)
                                            .addComponent(jSeparator33, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel47)
                                            .addComponent(nombreCarril2, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                            .addComponent(jSeparator28))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel48)
                                            .addComponent(nombreCarril3)
                                            .addComponent(jSeparator29, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel49)
                                            .addComponent(nombreCarril4)
                                            .addComponent(jSeparator30, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel53)
                                            .addComponent(nombreCarril8)
                                            .addComponent(jSeparator34, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel54)
                                            .addComponent(nombreCarril9)
                                            .addComponent(jSeparator35, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel55)
                                            .addComponent(nombreCarril10)
                                            .addComponent(jSeparator36, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(rSButtonMetro2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rSButtonMetro3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel49)
                                .addGap(2, 2, 2)
                                .addComponent(nombreCarril4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator30, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nombreCarrilBusqueda4)
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel47)
                                        .addGap(2, 2, 2)
                                        .addComponent(nombreCarril2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jSeparator28, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel48)
                                        .addGap(2, 2, 2)
                                        .addComponent(nombreCarril3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jSeparator29, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel52)
                                .addGap(2, 2, 2)
                                .addComponent(nombreCarril7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator33, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel50)
                                .addGap(2, 2, 2)
                                .addComponent(nombreCarril5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator31, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel51)
                                .addGap(2, 2, 2)
                                .addComponent(nombreCarril6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator32, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel55)
                                .addGap(2, 2, 2)
                                .addComponent(nombreCarril10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator36, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel53)
                                .addGap(2, 2, 2)
                                .addComponent(nombreCarril8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator34, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel54)
                                .addGap(2, 2, 2)
                                .addComponent(nombreCarril9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator35, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rSButtonMetro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rSButtonMetro3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMetro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro3ActionPerformed
        // TODO add your handling code here
        int pregunta = JOptionPane.showConfirmDialog(null, "¿Realmente desea reportar este vehiculo?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (pregunta == 0) {
            JOptionPane.showMessageDialog(this, "REportar");
        } else {
            JOptionPane.showMessageDialog(this, "No REportar");
        }
    }//GEN-LAST:event_rSButtonMetro3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Loggin l = new Loggin();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void modoNocturnoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoNocturnoBtnActionPerformed
        // TODO add your handling code here:
        modNoc = modNoc * -1;
        Color negroMelo = new Color(51, 51, 51);
        Color grisMasClaro = new Color(122, 122, 122);
        Color grisClarito = new Color(245, 245, 245);
        Color grisClaro = new Color(102, 102, 102);
        Color azulMelo = new Color(73, 171, 213);//azul principal
        Color azulMelo2 = new Color(63, 192, 220);
        if (modNoc == 1) {
            //modo dia
            jPanel4.setBackground(azulMelo);
            jPanel1.setBackground(Color.white);
            botonsito.setColorHover(azulMelo2);
            botonsito.setColorNormal(azulMelo);
            botonsito.setColorPressed(azulMelo);
            jPanel1.setBackground(grisClarito);
            nombreCarril2.setBackground(Color.white);
                    nombreCarril3.setBackground(Color.white);
            nombreCarril4.setBackground(Color.white);
                    nombreCarril5.setBackground(Color.white);
            nombreCarril6.setBackground(Color.white);
                    nombreCarril7.setBackground(Color.white);
            nombreCarril8.setBackground(Color.white);
                    nombreCarril9.setBackground(Color.white);
            nombreCarril10.setBackground(Color.white);
            nombreCarril2.setForeground(Color.white);
                    nombreCarril3.setForeground(azulMelo);
            nombreCarril4.setForeground(azulMelo);
                    nombreCarril5.setForeground(azulMelo);
            nombreCarril6.setForeground(azulMelo);
                    nombreCarril7.setForeground(azulMelo);
            nombreCarril8.setForeground(azulMelo);
                    nombreCarril9.setForeground(azulMelo);
            nombreCarril10.setForeground(azulMelo);
        } else {
            //modo noche
            jPanel4.setBackground(negroMelo);
            botonsito.setColorHover(grisMasClaro);
            botonsito.setColorNormal(negroMelo);
            botonsito.setColorPressed(negroMelo);
            jPanel1.setBackground(grisMasClaro);
            jPanel1.setBackground(grisClaro);
            nombreCarril2.setBackground(grisClaro);
                    nombreCarril3.setBackground(grisClaro);
            nombreCarril4.setBackground(grisClaro);
                    nombreCarril5.setBackground(grisClaro);
            nombreCarril6.setBackground(grisClaro);
                    nombreCarril7.setBackground(grisClaro);
            nombreCarril8.setBackground(grisClaro);
                    nombreCarril9.setBackground(grisClaro);
            nombreCarril10.setBackground(grisClaro);
            nombreCarril2.setForeground(grisClaro);
                    nombreCarril3.setForeground(Color.white);
            nombreCarril4.setForeground(Color.white);
                    nombreCarril5.setForeground(Color.white);
            nombreCarril6.setForeground(Color.white);
                    nombreCarril7.setForeground(Color.white);
            nombreCarril8.setForeground(Color.white);
                    nombreCarril9.setForeground(Color.white);
            nombreCarril10.setForeground(Color.white);
        }
    }//GEN-LAST:event_modoNocturnoBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VenPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VenPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VenPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VenPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VenPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro botonsito;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator31;
    private javax.swing.JSeparator jSeparator32;
    private javax.swing.JSeparator jSeparator33;
    private javax.swing.JSeparator jSeparator34;
    private javax.swing.JSeparator jSeparator35;
    private javax.swing.JSeparator jSeparator36;
    private javax.swing.JButton modoNocturnoBtn;
    private javax.swing.JTextField nombreCarril10;
    private javax.swing.JTextField nombreCarril2;
    private javax.swing.JTextField nombreCarril3;
    private javax.swing.JTextField nombreCarril4;
    private javax.swing.JTextField nombreCarril5;
    private javax.swing.JTextField nombreCarril6;
    private javax.swing.JTextField nombreCarril7;
    private javax.swing.JTextField nombreCarril8;
    private javax.swing.JTextField nombreCarril9;
    private javax.swing.JLabel nombreCarrilBusqueda4;
    private rsbuttom.RSButtonMetro rSButtonMetro2;
    private rsbuttom.RSButtonMetro rSButtonMetro3;
    // End of variables declaration//GEN-END:variables
}
