/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

<<<<<<< HEAD
<<<<<<< HEAD
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Time;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
=======
import java.awt.Color;
>>>>>>> a1a640f70cf05e1979ab0bb2c009d82abdd79851
=======
import java.awt.Color;
>>>>>>> a1a640f70cf05e1979ab0bb2c009d82abdd79851
import javax.swing.JOptionPane;
import logica.CarrilLogica;
import logica.CategoriaLogica;
import logica.EmpleadoLogica;
import logica.FacturaLogica;
import modelo.Carril;
import modelo.Categoria;
import modelo.Empleado;
import modelo.Factura;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRExporter;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.export.JRPdfExporter;
import net.sf.jasperreports.view.JasperViewer;
import static vista.Loggin.cedulaEmpleado;

/**
 *
 * @author Duvan Quevedo
 */
public class VenPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VenPrincipal
     */
    int modNoc = -1;

    public VenPrincipal() {
        initComponents();
        inPlaca.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        modoNocturnoBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        botonsito = new rsbuttom.RSButtonMetro();
        jLabel47 = new javax.swing.JLabel();
        inIdFactura = new javax.swing.JTextField();
        jSeparator28 = new javax.swing.JSeparator();
        nombreCarrilBusqueda4 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        inPlaca = new javax.swing.JTextField();
        jSeparator29 = new javax.swing.JSeparator();
        jLabel49 = new javax.swing.JLabel();
        inCategoria = new javax.swing.JTextField();
        jSeparator30 = new javax.swing.JSeparator();
        jLabel50 = new javax.swing.JLabel();
        inIdCarril = new javax.swing.JTextField();
        jSeparator31 = new javax.swing.JSeparator();
        jSeparator32 = new javax.swing.JSeparator();
        inCedula = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        inFecha = new javax.swing.JTextField();
        jSeparator33 = new javax.swing.JSeparator();
        jLabel53 = new javax.swing.JLabel();
        inHora = new javax.swing.JTextField();
        jSeparator34 = new javax.swing.JSeparator();
        jLabel54 = new javax.swing.JLabel();
        inPrecioPagar = new javax.swing.JTextField();
        jSeparator35 = new javax.swing.JSeparator();
        jLabel55 = new javax.swing.JLabel();
        inPagoCliente = new javax.swing.JTextField();
        jSeparator36 = new javax.swing.JSeparator();
        btnFacturar = new rsbuttom.RSButtonMetro();
        btnReporte = new rsbuttom.RSButtonMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-exit.png"))); // NOI18N
        jButton1.setText("Cerrar sesión");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        modoNocturnoBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        modoNocturnoBtn.setForeground(new java.awt.Color(52, 152, 219));
        modoNocturnoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-idea-30.png"))); // NOI18N
        modoNocturnoBtn.setText("Modo nocturno");
        modoNocturnoBtn.setBorderPainted(false);
        modoNocturnoBtn.setContentAreaFilled(false);
        modoNocturnoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modoNocturnoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(modoNocturnoBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(modoNocturnoBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(73, 171, 213));

        botonsito.setText("Facturar");
        botonsito.setColorHover(new java.awt.Color(73, 171, 213));
        botonsito.setColorNormal(new java.awt.Color(63, 192, 220));
        botonsito.setColorPressed(new java.awt.Color(73, 171, 213));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonsito, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(botonsito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel47.setFont(new java.awt.Font("ClementePDai", 0, 18)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(73, 171, 213));
        jLabel47.setText("ID factura");

        inIdFactura.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        inIdFactura.setForeground(new java.awt.Color(73, 171, 213));
        inIdFactura.setBorder(null);
        inIdFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inIdFacturaActionPerformed(evt);
            }
        });

        nombreCarrilBusqueda4.setBackground(new java.awt.Color(245, 245, 245));
        nombreCarrilBusqueda4.setFont(new java.awt.Font("ClementePDai", 0, 24)); // NOI18N
        nombreCarrilBusqueda4.setForeground(new java.awt.Color(73, 171, 213));
        nombreCarrilBusqueda4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreCarrilBusqueda4.setText("Factura");

        jLabel48.setFont(new java.awt.Font("ClementePDai", 0, 18)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(73, 171, 213));
        jLabel48.setText("Placa");

        inPlaca.setBackground(new java.awt.Color(255, 255, 255));
        inPlaca.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        inPlaca.setForeground(new java.awt.Color(73, 171, 213));
        inPlaca.setBorder(null);
        inPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inPlacaActionPerformed(evt);
            }
        });
        inPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inPlacaKeyTyped(evt);
            }
        });

        jLabel49.setFont(new java.awt.Font("ClementePDai", 0, 18)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(73, 171, 213));
        jLabel49.setText("Categoria");

        inCategoria.setEditable(false);
        inCategoria.setBackground(new java.awt.Color(255, 255, 255));
        inCategoria.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        inCategoria.setForeground(new java.awt.Color(73, 171, 213));
        inCategoria.setBorder(null);

        jLabel50.setFont(new java.awt.Font("ClementePDai", 0, 18)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(73, 171, 213));
        jLabel50.setText("ID carril");

        inIdCarril.setEditable(false);
        inIdCarril.setBackground(new java.awt.Color(255, 255, 255));
        inIdCarril.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        inIdCarril.setForeground(new java.awt.Color(73, 171, 213));
        inIdCarril.setBorder(null);

        inCedula.setEditable(false);
        inCedula.setBackground(new java.awt.Color(255, 255, 255));
        inCedula.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        inCedula.setForeground(new java.awt.Color(73, 171, 213));
        inCedula.setBorder(null);

        jLabel51.setFont(new java.awt.Font("ClementePDai", 0, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(73, 171, 213));
        jLabel51.setText("Cedula propietario");

        jLabel52.setFont(new java.awt.Font("ClementePDai", 0, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(73, 171, 213));
        jLabel52.setText("fecha");

        inFecha.setEditable(false);
        inFecha.setBackground(new java.awt.Color(255, 255, 255));
        inFecha.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        inFecha.setForeground(new java.awt.Color(73, 171, 213));
        inFecha.setBorder(null);

        jLabel53.setFont(new java.awt.Font("ClementePDai", 0, 18)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(73, 171, 213));
        jLabel53.setText("Hora");

        inHora.setEditable(false);
        inHora.setBackground(new java.awt.Color(255, 255, 255));
        inHora.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        inHora.setForeground(new java.awt.Color(73, 171, 213));
        inHora.setBorder(null);

        jLabel54.setFont(new java.awt.Font("ClementePDai", 0, 18)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(73, 171, 213));
        jLabel54.setText("Precio a pagar");

        inPrecioPagar.setEditable(false);
        inPrecioPagar.setBackground(new java.awt.Color(255, 255, 255));
        inPrecioPagar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        inPrecioPagar.setForeground(new java.awt.Color(73, 171, 213));
        inPrecioPagar.setBorder(null);

        jLabel55.setFont(new java.awt.Font("ClementePDai", 0, 18)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(73, 171, 213));
        jLabel55.setText("Pago");

        inPagoCliente.setBackground(new java.awt.Color(255, 255, 255));
        inPagoCliente.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        inPagoCliente.setForeground(new java.awt.Color(73, 171, 213));
        inPagoCliente.setBorder(null);
        inPagoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inPagoClienteKeyTyped(evt);
            }
        });

        btnFacturar.setText("Facturar");
        btnFacturar.setColorHover(new java.awt.Color(73, 171, 213));
        btnFacturar.setColorNormal(new java.awt.Color(63, 192, 220));
        btnFacturar.setColorPressed(new java.awt.Color(73, 171, 213));
        btnFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturarActionPerformed(evt);
            }
        });

        btnReporte.setText("Reportar");
        btnReporte.setColorHover(new java.awt.Color(221, 75, 57));
        btnReporte.setColorNormal(new java.awt.Color(221, 75, 80));
        btnReporte.setColorPressed(new java.awt.Color(221, 75, 57));
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(nombreCarrilBusqueda4, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel50)
                                            .addComponent(inIdCarril)
                                            .addComponent(jSeparator31, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel51)
                                            .addComponent(inCedula)
                                            .addComponent(jSeparator32, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel52)
                                            .addComponent(inFecha)
                                            .addComponent(jSeparator33, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel47)
                                            .addComponent(inIdFactura, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                            .addComponent(jSeparator28))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel48)
                                            .addComponent(inPlaca)
                                            .addComponent(jSeparator29, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel49)
                                            .addComponent(inCategoria)
                                            .addComponent(jSeparator30, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel53)
                                            .addComponent(inHora)
                                            .addComponent(jSeparator34, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel54)
                                            .addComponent(inPrecioPagar)
                                            .addComponent(jSeparator35, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel55)
                                            .addComponent(inPagoCliente)
                                            .addComponent(jSeparator36, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(btnFacturar, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel49)
                                .addGap(2, 2, 2)
                                .addComponent(inCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator30, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nombreCarrilBusqueda4)
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel47)
                                        .addGap(2, 2, 2)
                                        .addComponent(inIdFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jSeparator28, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel48)
                                        .addGap(2, 2, 2)
                                        .addComponent(inPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jSeparator29, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel52)
                                .addGap(2, 2, 2)
                                .addComponent(inFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator33, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel50)
                                .addGap(2, 2, 2)
                                .addComponent(inIdCarril, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator31, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel51)
                                .addGap(2, 2, 2)
                                .addComponent(inCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator32, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel55)
                                .addGap(2, 2, 2)
                                .addComponent(inPagoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator36, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel53)
                                .addGap(2, 2, 2)
                                .addComponent(inHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator34, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel54)
                                .addGap(2, 2, 2)
                                .addComponent(inPrecioPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator35, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFacturar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        inPlaca.requestFocus();
        int pregunta = JOptionPane.showConfirmDialog(null, "¿Realmente desea reportar este vehiculo?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (pregunta == 0) {
            JOptionPane.showMessageDialog(this, "REportar");
        } else {
            JOptionPane.showMessageDialog(this, "No REportar");
        }
    }//GEN-LAST:event_btnReporteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Loggin l = new Loggin();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

<<<<<<< HEAD
<<<<<<< HEAD
    private void btnFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturarActionPerformed
        try {                                            
            String a = inIdFactura.getText();
            String placa = "", tipovehiculo = "";
            inPagoCliente.getText();
            if(inPrecioPagar.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Compruebe si ha realizado la busqueda de la placa.");
            }
            if(inPagoCliente.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "Ingrese el dinero entregado por el cliente.");
                inPagoCliente.requestFocus();
                return;
            }else if(Integer.parseInt(inPagoCliente.getText())< Integer.parseInt(inPrecioPagar.getText())){
                JOptionPane.showMessageDialog(this, "El dinero entregado por el cliente es menor, intentelo de nuevo.");
                inPagoCliente.requestFocus();
                return;
            }
            JOptionPane.showMessageDialog(this, "El cambio a dar es " + (Integer.parseInt(inPrecioPagar.getText())-Integer.parseInt(inPagoCliente.getText())) + ".");
            Date d = new Date();
            System.out.println(d);
            Factura f = new Factura(Integer.parseInt(inIdFactura.getText()), d, d, Double.parseDouble(inPagoCliente.getText()),( Double.parseDouble(inPrecioPagar.getText())-Double.parseDouble(inPagoCliente.getText())));
            f.setCategoria(new CategoriaLogica().buscarCategoria(new Categoria(inCategoria.getText())));
            f.setIdcarril(new CarrilLogica().buscarCarril(new Carril(Integer.parseInt(inIdCarril.getText()))));
            System.out.println(cedulaEmpleado);
            f.setCedula(new EmpleadoLogica().buscarEmpleado(new Empleado(cedulaEmpleado)));
            f.setPlaca(inPlaca.getText());
            
            System.out.println(f.getIdfactura());
            try {
                new FacturaLogica().registarFactura(f);
            } catch (Exception ex) {
                Logger.getLogger(VenPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            Class.forName("org.postgresql.Driver");
            java.sql.Connection conexion = DriverManager.getConnection("jdbc:postgresql://192.168.0.19:5432/Peaje", "postgres", "123");
            
            Map<String, Object> parametros = new HashMap<>();
            parametros.put("idFac", f.getIdfactura());
JasperCompileManager.compileReportToFile(
                "Factura.jrxml",//the path to the jrxml file to compile
                "Factura.jasper");
            JasperPrint jp = JasperFillManager.fillReport("C:\\Users\\Usuario\\Desktop\\UUUUUU\\AAAAAA\\PeajeSoft\\src\\reporte\\Factura.jasper", parametros, conexion);
            JasperViewer jv = new JasperViewer(jp, false);
            jv.setVisible(true);

            JRExporter exporter = new JRPdfExporter();
            //   String a = "Factura" + Integer.parseInt(modelo.getValueAt(tablaFactura.getSelectedRow(), 0).toString()) + ".pdf";
            exporter.setParameter(JRExporterParameter.JASPER_PRINT, jp);
            exporter.setParameter(JRExporterParameter.OUTPUT_FILE, new java.io.File(a));
            
            
            
            
            
            
            
            inPlaca.setText("");
            inPlaca.requestFocus();
            inCategoria.setText("");
            inCedula.setText("");
            inPrecioPagar.setText("");
            int t =Integer.parseInt( inIdFactura.getText())+1;
            inIdFactura.setText(String.valueOf(t));
            inFecha.setText("");
            inHora.setText("");
            
            //Factura f = new FacturaLogica().registarFactura(new Factura(0, d, t, ERROR, HEIGHT))
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VenPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(VenPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(VenPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFacturarActionPerformed

    private void inIdFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inIdFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inIdFacturaActionPerformed

    private void inPlacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inPlacaKeyTyped

        int key = evt.getKeyChar();
        System.out.println(key);
        if (key==KeyEvent.VK_ENTER ) {
            inPagoCliente.requestFocus();
            evt.consume();
            String a = inPlaca.getText().toUpperCase();
            String placa = "", tipovehiculo = "", cedula = "";
            Date d = new Date();
            System.out.println(d.toString());
            Time t = new Time(0);
            System.out.println(t.toString()); 
            DateFormat hourFormat = new SimpleDateFormat("HH:mm:ss");
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            try {
                Class.forName("org.postgresql.Driver");
                Connection con = DriverManager.getConnection("jdbc:postgresql://192.168.0.28:5432/transito", "peajeUnivalle", "123456");
                PreparedStatement pst = con.prepareStatement("SELECT * FROM vehiculo Where placa=" + "'" + a + "';");
                ResultSet rs = pst.executeQuery();
                ResultSetMetaData rsm = rs.getMetaData();
                while (rs.next()) {
                    System.out.println(rs.getString(1));
                    placa = rs.getString(1);
                    cedula = rs.getString(2);
                    tipovehiculo = rs.getString(3);
                }
                
                if(tipovehiculo.equals("HUMANITARIO")){
                    JOptionPane.showMessageDialog(this, "Carro de ayuda Humanitaria. Se dara paso automanticamente.");
                    inPlaca.setText("");
                    inPlaca.requestFocus();
                    return;
                }
                try {
                    inIdFactura.setText(String.valueOf(new FacturaLogica().consultarTodos().size()+1));
                } catch (Exception ex) {
                    Logger.getLogger(VenPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
                inCategoria.setText(tipovehiculo);
                inIdCarril.setText("1");
                inCedula.setText(cedula);
                inFecha.setText(dateFormat.format(d));
                inHora.setText(hourFormat.format(d));
                Categoria ca = new CategoriaLogica().buscarCategoria(new Categoria(tipovehiculo));
                int h=(int) ca.getPrecio();
                inPrecioPagar.setText(String.valueOf(h));
                inPagoCliente.getText();

                System.out.println(tipovehiculo);
                if (placa.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "LLAME AL PERSONAL DE SEGURIDAD, PLACA NO ENCONTRADA.");
                    return;
                }

            } catch (SQLException ex) {
                Logger.getLogger(VenPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(VenPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_inPlacaKeyTyped

    private void inPagoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inPagoClienteKeyTyped
        char c = evt.getKeyChar();
        int i = evt.getKeyChar();
        if (i==KeyEvent.VK_ENTER) {
            evt.consume();
            btnFacturarActionPerformed(null);
        } 
        if (i==KeyEvent.VK_HOME) {
            evt.consume();
            btnReporteActionPerformed(null);
        } 
        if (inPagoCliente.getText().length() >= 7) {
            evt.consume();
        }
               // TODO add your handling code here:
    }//GEN-LAST:event_inPagoClienteKeyTyped

    private void inPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inPlacaActionPerformed
=======
=======
>>>>>>> a1a640f70cf05e1979ab0bb2c009d82abdd79851
    private void modoNocturnoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modoNocturnoBtnActionPerformed
        // TODO add your handling code here:
        modNoc = modNoc * -1;
        Color negroMelo = new Color(51, 51, 51);
        Color grisMasClaro = new Color(122, 122, 122);
        Color grisClarito = new Color(245, 245, 245);
        Color grisClaro = new Color(102, 102, 102);
        Color azulMelo = new Color(73, 171, 213);//azul principal
        Color azulMelo2 = new Color(63, 192, 220);
        if (modNoc == 1) {
            //modo dia
            jPanel4.setBackground(azulMelo);
            jPanel1.setBackground(Color.white);
            botonsito.setColorHover(azulMelo2);
            botonsito.setColorNormal(azulMelo);
            botonsito.setColorPressed(azulMelo);
            jPanel1.setBackground(grisClarito);
            nombreCarril2.setBackground(Color.white);
                    nombreCarril3.setBackground(Color.white);
            nombreCarril4.setBackground(Color.white);
                    nombreCarril5.setBackground(Color.white);
            nombreCarril6.setBackground(Color.white);
                    nombreCarril7.setBackground(Color.white);
            nombreCarril8.setBackground(Color.white);
                    nombreCarril9.setBackground(Color.white);
            nombreCarril10.setBackground(Color.white);
            nombreCarril2.setForeground(Color.white);
                    nombreCarril3.setForeground(azulMelo);
            nombreCarril4.setForeground(azulMelo);
                    nombreCarril5.setForeground(azulMelo);
            nombreCarril6.setForeground(azulMelo);
                    nombreCarril7.setForeground(azulMelo);
            nombreCarril8.setForeground(azulMelo);
                    nombreCarril9.setForeground(azulMelo);
            nombreCarril10.setForeground(azulMelo);
        } else {
            //modo noche
            jPanel4.setBackground(negroMelo);
            botonsito.setColorHover(grisMasClaro);
            botonsito.setColorNormal(negroMelo);
            botonsito.setColorPressed(negroMelo);
            jPanel1.setBackground(grisMasClaro);
            jPanel1.setBackground(grisClaro);
            nombreCarril2.setBackground(grisClaro);
                    nombreCarril3.setBackground(grisClaro);
            nombreCarril4.setBackground(grisClaro);
                    nombreCarril5.setBackground(grisClaro);
            nombreCarril6.setBackground(grisClaro);
                    nombreCarril7.setBackground(grisClaro);
            nombreCarril8.setBackground(grisClaro);
                    nombreCarril9.setBackground(grisClaro);
            nombreCarril10.setBackground(grisClaro);
            nombreCarril2.setForeground(grisClaro);
                    nombreCarril3.setForeground(Color.white);
            nombreCarril4.setForeground(Color.white);
                    nombreCarril5.setForeground(Color.white);
            nombreCarril6.setForeground(Color.white);
                    nombreCarril7.setForeground(Color.white);
            nombreCarril8.setForeground(Color.white);
                    nombreCarril9.setForeground(Color.white);
            nombreCarril10.setForeground(Color.white);
        }
    }//GEN-LAST:event_modoNocturnoBtnActionPerformed
<<<<<<< HEAD
>>>>>>> a1a640f70cf05e1979ab0bb2c009d82abdd79851
=======
>>>>>>> a1a640f70cf05e1979ab0bb2c009d82abdd79851

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VenPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VenPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VenPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VenPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VenPrincipal().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
<<<<<<< HEAD
<<<<<<< HEAD
    private rsbuttom.RSButtonMetro btnFacturar;
    private rsbuttom.RSButtonMetro btnReporte;
    private javax.swing.JTextField inCategoria;
    private javax.swing.JTextField inCedula;
    private javax.swing.JTextField inFecha;
    private javax.swing.JTextField inHora;
    private javax.swing.JTextField inIdCarril;
    private javax.swing.JTextField inIdFactura;
    private javax.swing.JTextField inPagoCliente;
    private javax.swing.JTextField inPlaca;
    private javax.swing.JTextField inPrecioPagar;
=======
    private rsbuttom.RSButtonMetro botonsito;
>>>>>>> a1a640f70cf05e1979ab0bb2c009d82abdd79851
=======
    private rsbuttom.RSButtonMetro botonsito;
>>>>>>> a1a640f70cf05e1979ab0bb2c009d82abdd79851
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator30;
    private javax.swing.JSeparator jSeparator31;
    private javax.swing.JSeparator jSeparator32;
    private javax.swing.JSeparator jSeparator33;
    private javax.swing.JSeparator jSeparator34;
    private javax.swing.JSeparator jSeparator35;
    private javax.swing.JSeparator jSeparator36;
<<<<<<< HEAD
<<<<<<< HEAD
    private javax.swing.JLabel nombreCarrilBusqueda4;
    private rsbuttom.RSButtonMetro rSButtonMetro1;
=======
=======
>>>>>>> a1a640f70cf05e1979ab0bb2c009d82abdd79851
    private javax.swing.JButton modoNocturnoBtn;
    private javax.swing.JTextField nombreCarril10;
    private javax.swing.JTextField nombreCarril2;
    private javax.swing.JTextField nombreCarril3;
    private javax.swing.JTextField nombreCarril4;
    private javax.swing.JTextField nombreCarril5;
    private javax.swing.JTextField nombreCarril6;
    private javax.swing.JTextField nombreCarril7;
    private javax.swing.JTextField nombreCarril8;
    private javax.swing.JTextField nombreCarril9;
    private javax.swing.JLabel nombreCarrilBusqueda4;
    private rsbuttom.RSButtonMetro rSButtonMetro2;
    private rsbuttom.RSButtonMetro rSButtonMetro3;
>>>>>>> a1a640f70cf05e1979ab0bb2c009d82abdd79851
    // End of variables declaration//GEN-END:variables
}
